[package]
name = "tess2"
version = "0.2.0"
authors = ["Payton Turnage <paytonturnage@gmail.com>"]
description = "libtess2 bindings and safe wrapper."
license = "MIT"

[dependencies]
itertools = "0.7.4"

[build-dependencies]
bindgen = "0.26.3"
