[package]
name = "tess2"
version = "0.3.0"
authors = ["Payton Turnage <paytonturnage@gmail.com>"]
description = "Safe wrapper around libtess2."
license = "MIT"
edition = "2018"

[dependencies.tess2-sys]
git = "https://github.com/piaoger/tess2-sys.git"
branch = "devel"
