[package]
name = "tess2"
version = "0.2.0"
authors = ["Payton Turnage <paytonturnage@gmail.com>"]
description = "Safe wrapper around libtess2."
license = "MIT"

[build-dependencies]
bindgen = "0.26.3"

[dependencies]
tess2-sys = { version = "0.2.0", path = "../sys" }
itertools = "0.7.4"

